### ISSUE TITLE
The linked normalize.css is not maintained it seems

### ISSUE THREAD

**Issue by viblo** [oxalorg/sakura#123]
In the readme it says its best to use a normalize.css in addition to sakura itself. Is this still relevant? The normalize.css linked leads to https://github.com/necolas/normalize.css/ but that seems unmaintained nowadays. Instead https://github.com/csstools/normalize.css has taken over from what I can tell.

Im not a very well experienced web dev, but imho it would be nice to have it merged into sakura.css itself so I only need to link one css file. I see there's an old issue about the opposite https://github.com/oxalorg/sakura/issues/9 but maybe things have changed since then?

Anyway, thanks for Sakura!

**Comment by ab-ba741** [comment]
> The normalize.css linked leads to https://github.com/necolas/normalize.css/ but that seems unmaintained nowadays. Instead https://github.com/csstools/normalize.css has taken over from what I can tell.

The repo it-self seems unmaintained

**Comment by oxalorg** [comment]
@viblo @shiroopi Normalize.css has been stable since a long time. Sure it could be more active but it works, it supports many older browser versions which many other normalize libraries don't.

The entire point of sakura (and normalize) is to give you a simple explicit starting point, with readable code, which you can then change bits and pieces of.

Similar for sakura I feel there are small improvements which can be made (And I will get to them eventually), but it's largely stable and works for most folks.
