### ISSUE TITLE
Sakura breaks Google CSE

### ISSUE THREAD

**Issue by viemmsakh** [oxalorg/sakura#13]
Saw this project on reddit and figured it would be something I could easily add to the website I inherited. Unfortunately the page was too broken to just "work" with Sakura and I decided to just re-write everything using sakura. Everything was going fine till I tried to add my Google CSE to the page. The CSS rules are interfering with how CSE renders on the page.

Sakura Enabled:
![image](https://cloud.githubusercontent.com/assets/1683382/25849329/0ed63bb8-348c-11e7-9004-308e7d78bc1b.png)

Sakura Disabled:
![image](https://cloud.githubusercontent.com/assets/1683382/25849356/2e0ec5ea-348c-11e7-8433-3d93082dfa4e.png)

**Edit**

My original screenshots just show the button being off, however the textarea is as well.

Enabled:
![image](https://cloud.githubusercontent.com/assets/1683382/25849649/50670ec6-348d-11e7-90b8-217ccbdbc5dc.png)

Disabled:
![image](https://cloud.githubusercontent.com/assets/1683382/25849665/60187a08-348d-11e7-968b-c7a89bbc79a9.png)

**Comment by oxalorg** [comment]
External css can surely interfere with sakura, especially if they are not extremely explicit. For instance, disqus works perfectly fine with sakura because they are overriding almost all of the rules they need for proper rendering.

I don't know much about Google CSE, but I'm sure you can customise the css/html they inject into your page. Or maybe just write the input box yourself and hook into javascript, here's an example of CSE which works pretty well with sakura: http://web.ccsu.edu/library/tomaiuolon/cse.htm (the first box)

If you can give me link to the page/code you're using CSE on, maybe I can help you out a little more.
