### ISSUE TITLE
Improve tooling

### ISSUE THREAD

**Issue by oxalorg** [oxalorg/sakura#77]
- Autogenerate css using GitHub actions, it should only commit if css files have changed
- If possible get rid of node-sass
- Improve release tooling

Need to spend some time thinking on how to improve the tooling so it's easier for contributions and for quicker releases.

Also moving over to using `css vars` gets more and more appealing as the years go by. Maybe that will simplify everything a lot!

**Comment by spenserblack** [comment]
It's a bit redundant since you already have a demo on your personal website, but it might be fun to automate previews with Vercel or some other tool. That way you can get per-PR builds so that you can review visual changes without having to pull down the code and run your test locally. https://github.com/spenserblack/fun-jp-terms/pull/13 is an example of a PR with an automated preview.

**Comment by oxalorg** [comment]
Fixed in #113
